-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  supabase_user_id uuid NOT NULL UNIQUE,
  email character varying NOT NULL UNIQUE,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['platform_admin'::character varying, 'super_admin'::character varying]::text[])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.app_users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone_number character varying UNIQUE,
  email character varying UNIQUE,
  first_name character varying,
  last_name character varying,
  date_of_birth date,
  is_verified boolean DEFAULT false,
  verification_code character varying,
  verification_expires_at timestamp with time zone,
  push_token character varying,
  preferences jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  reservation_no_show_count integer DEFAULT 0 CHECK (reservation_no_show_count >= 0),
  reservation_blocked_until timestamp with time zone,
  CONSTRAINT app_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.article_pricing (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  article_id uuid NOT NULL,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  start_time time without time zone,
  end_time time without time zone,
  start_date date,
  end_date date,
  days_of_week ARRAY,
  priority integer DEFAULT 0,
  name character varying,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT article_pricing_pkey PRIMARY KEY (id),
  CONSTRAINT article_pricing_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.articles(id)
);
CREATE TABLE public.article_qr_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shop_id uuid NOT NULL,
  article_id uuid NOT NULL,
  qr_code character varying NOT NULL,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'used'::character varying]::text[])),
  used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT article_qr_codes_pkey PRIMARY KEY (id),
  CONSTRAINT article_qr_codes_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id),
  CONSTRAINT article_qr_codes_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.articles(id)
);
CREATE TABLE public.articles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shop_id uuid NOT NULL,
  pos_article_id character varying NOT NULL,
  name character varying NOT NULL,
  base_price numeric NOT NULL CHECK (base_price >= 0::numeric),
  description text,
  category character varying,
  type character varying,
  tax_type character varying,
  tax_rate numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT articles_pkey PRIMARY KEY (id),
  CONSTRAINT articles_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id)
);
CREATE TABLE public.coupon_redemptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  coupon_id uuid NOT NULL,
  app_user_id uuid NOT NULL,
  transaction_id uuid,
  points_deducted integer DEFAULT 0,
  discount_applied numeric DEFAULT 0,
  redeemed_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'used'::character varying, 'expired'::character varying, 'cancelled'::character varying]::text[])),
  redemption_code character varying UNIQUE,
  CONSTRAINT coupon_redemptions_pkey PRIMARY KEY (id),
  CONSTRAINT coupon_redemptions_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES public.coupons(id),
  CONSTRAINT coupon_redemptions_app_user_id_fkey FOREIGN KEY (app_user_id) REFERENCES public.app_users(id),
  CONSTRAINT coupon_redemptions_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.coupons (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shop_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['percentage'::character varying, 'fixed'::character varying]::text[])),
  description text,
  expires_at timestamp with time zone,
  used_count integer DEFAULT 0 CHECK (used_count >= 0),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  points_required integer CHECK (points_required >= 0),
  image_url character varying,
  name character varying NOT NULL,
  articles_data jsonb NOT NULL CHECK (jsonb_typeof(articles_data) = 'array'::text),
  CONSTRAINT coupons_pkey PRIMARY KEY (id),
  CONSTRAINT coupons_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id)
);
CREATE TABLE public.customer_loyalty_accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  app_user_id uuid NOT NULL,
  shop_id uuid NOT NULL,
  points_balance integer DEFAULT 0 CHECK (points_balance >= 0),
  total_spent numeric DEFAULT 0 CHECK (total_spent >= 0::numeric),
  last_visit_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  total_points_earned integer DEFAULT 0 CHECK (total_points_earned >= 0),
  total_points_redeemed integer DEFAULT 0 CHECK (total_points_redeemed >= 0),
  invoice_count integer DEFAULT 0 CHECK (invoice_count >= 0),
  CONSTRAINT customer_loyalty_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT customer_loyalty_accounts_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id),
  CONSTRAINT customer_loyalty_accounts_app_user_id_fkey FOREIGN KEY (app_user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['platform'::character varying, 'enterprise'::character varying, 'external-qr-codes'::character varying]::text[])),
  subscription_tier character varying CHECK (subscription_tier::text = ANY (ARRAY['basic'::character varying, 'premium'::character varying, 'enterprise'::character varying]::text[])),
  database_config jsonb,
  settings jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.loyalty_programs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shop_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['points'::character varying, 'stamps'::character varying, 'visits'::character varying]::text[])),
  name character varying NOT NULL,
  description text,
  points_per_euro numeric CHECK (points_per_euro >= 0::numeric),
  stamps_required integer CHECK (stamps_required > 0),
  visits_required integer CHECK (visits_required > 0),
  reward_description text,
  reward_value numeric,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_programs_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_programs_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id)
);
CREATE TABLE public.notification_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shop_id uuid NOT NULL,
  name character varying NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['birthday'::character varying, 'manual'::character varying, 'points_earned'::character varying, 'coupon_ready'::character varying]::text[])),
  title character varying NOT NULL,
  body text NOT NULL,
  data jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_templates_pkey PRIMARY KEY (id),
  CONSTRAINT notification_templates_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id)
);
CREATE TABLE public.pos_providers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  description text,
  api_key character varying NOT NULL UNIQUE,
  webhook_url character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pos_providers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.push_notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shop_id uuid,
  app_user_id uuid,
  notification_type character varying NOT NULL,
  title character varying NOT NULL,
  body text NOT NULL,
  data jsonb DEFAULT '{}'::jsonb,
  expo_ticket_id character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'delivered'::character varying, 'failed'::character varying, 'error'::character varying]::text[])),
  error_message text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT push_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT push_notifications_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id),
  CONSTRAINT push_notifications_app_user_id_fkey FOREIGN KEY (app_user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.push_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  app_user_id uuid NOT NULL,
  expo_push_token character varying NOT NULL UNIQUE,
  device_info jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT push_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT push_tokens_app_user_id_fkey FOREIGN KEY (app_user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.reservation_availability (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shop_id uuid NOT NULL,
  resource_id uuid,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reservation_availability_pkey PRIMARY KEY (id),
  CONSTRAINT reservation_availability_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id),
  CONSTRAINT reservation_availability_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.reservation_resources(id)
);
CREATE TABLE public.reservation_blocks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shop_id uuid NOT NULL,
  resource_id uuid,
  start_datetime timestamp with time zone NOT NULL,
  end_datetime timestamp with time zone NOT NULL,
  reason character varying,
  block_type character varying DEFAULT 'custom'::character varying CHECK (block_type::text = ANY (ARRAY['holiday'::character varying, 'vacation'::character varying, 'break'::character varying, 'custom'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reservation_blocks_pkey PRIMARY KEY (id),
  CONSTRAINT reservation_blocks_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id),
  CONSTRAINT reservation_blocks_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.reservation_resources(id)
);
CREATE TABLE public.reservation_reminders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  reservation_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['push'::character varying, 'sms'::character varying, 'email'::character varying]::text[])),
  scheduled_for timestamp with time zone NOT NULL,
  sent_at timestamp with time zone,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reservation_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT reservation_reminders_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES public.reservations(id)
);
CREATE TABLE public.reservation_resource_services (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resource_id uuid NOT NULL,
  service_id uuid NOT NULL,
  price_override numeric CHECK (price_override >= 0::numeric),
  duration_override integer CHECK (duration_override > 0),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reservation_resource_services_pkey PRIMARY KEY (id),
  CONSTRAINT reservation_resource_services_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.reservation_resources(id),
  CONSTRAINT reservation_resource_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.reservation_services(id)
);
CREATE TABLE public.reservation_resources (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shop_id uuid NOT NULL,
  name character varying NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['staff'::character varying, 'table'::character varying, 'room'::character varying, 'other'::character varying]::text[])),
  image_url character varying,
  description text,
  specialties jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reservation_resources_pkey PRIMARY KEY (id),
  CONSTRAINT reservation_resources_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id)
);
CREATE TABLE public.reservation_services (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shop_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  duration_minutes integer,
  price numeric CHECK (price >= 0::numeric),
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['service'::character varying, 'table'::character varying, 'slot'::character varying]::text[])),
  capacity integer DEFAULT 1 CHECK (capacity >= 1),
  requires_resource boolean DEFAULT true,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reservation_services_pkey PRIMARY KEY (id),
  CONSTRAINT reservation_services_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id)
);
CREATE TABLE public.reservations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shop_id uuid NOT NULL,
  service_id uuid NOT NULL,
  resource_id uuid,
  app_user_id uuid,
  guest_name character varying,
  guest_phone character varying,
  guest_email character varying,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone,
  party_size integer DEFAULT 1 CHECK (party_size >= 1),
  price numeric,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'cancelled'::character varying, 'completed'::character varying, 'no_show'::character varying]::text[])),
  confirmation_mode character varying CHECK (confirmation_mode::text = ANY (ARRAY['auto'::character varying, 'manual'::character varying]::text[])),
  confirmed_at timestamp with time zone,
  confirmed_by character varying,
  cancelled_at timestamp with time zone,
  cancelled_by character varying,
  cancellation_reason text,
  no_show_marked_at timestamp with time zone,
  no_show_marked_by character varying,
  customer_notes text,
  internal_notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reservations_pkey PRIMARY KEY (id),
  CONSTRAINT reservations_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id),
  CONSTRAINT reservations_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.reservation_services(id),
  CONSTRAINT reservations_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.reservation_resources(id),
  CONSTRAINT reservations_app_user_id_fkey FOREIGN KEY (app_user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.shop_owner_invitations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shop_id uuid NOT NULL,
  email character varying NOT NULL,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  phone character varying,
  invitation_token character varying NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'expired'::character varying, 'cancelled'::character varying]::text[])),
  invited_by character varying,
  completed_at timestamp with time zone,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  invited_by_admin uuid,
  CONSTRAINT shop_owner_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT shop_owner_invitations_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id),
  CONSTRAINT shop_owner_invitations_invited_by_admin_fkey FOREIGN KEY (invited_by_admin) REFERENCES public.admin_users(id)
);
CREATE TABLE public.shops (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid NOT NULL,
  pos_provider_id uuid NOT NULL,
  pos_shop_id character varying,
  name character varying NOT NULL,
  description text,
  address text,
  phone character varying,
  email character varying,
  type character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'pending_setup'::character varying, 'active'::character varying, 'suspended'::character varying, 'inactive'::character varying]::text[])),
  approved_by character varying,
  approved_at timestamp with time zone,
  pos_synced_at timestamp with time zone,
  pos_sync_data jsonb,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  opening_hours character varying,
  loyalty_type character varying DEFAULT 'points'::character varying CHECK (loyalty_type::text = ANY (ARRAY['points'::character varying, 'coupons'::character varying]::text[])),
  website character varying,
  social_media jsonb DEFAULT '{}'::jsonb,
  owner_user_id uuid,
  image_url character varying,
  tag character varying,
  points_per_euro integer DEFAULT 100 CHECK (points_per_euro >= 1),
  qr_display_text character varying,
  shop_category character varying CHECK (shop_category::text = ANY (ARRAY['bar'::character varying, 'restaurant'::character varying, 'bakery'::character varying, 'wellness'::character varying, 'pastry'::character varying, 'cafe'::character varying, 'retail'::character varying, 'other'::character varying]::text[])),
  brand_color character varying,
  external_qr_codes_enabled boolean DEFAULT false,
  reservations_enabled boolean DEFAULT false,
  reservation_settings jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT shops_pkey PRIMARY KEY (id),
  CONSTRAINT shops_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT shops_pos_provider_id_fkey FOREIGN KEY (pos_provider_id) REFERENCES public.pos_providers(id)
);
CREATE TABLE public.transaction_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  transaction_id uuid NOT NULL,
  action character varying NOT NULL,
  details jsonb DEFAULT '{}'::jsonb,
  performed_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transaction_logs_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_logs_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shop_id uuid NOT NULL,
  pos_invoice_id character varying NOT NULL,
  transaction_number bigint NOT NULL DEFAULT nextval('transactions_transaction_number_seq'::regclass),
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  tax_amount numeric DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  items jsonb NOT NULL,
  app_user_id uuid,
  loyalty_account_id uuid,
  loyalty_points_awarded integer DEFAULT 0 CHECK (loyalty_points_awarded >= 0),
  loyalty_stamps_awarded integer DEFAULT 0 CHECK (loyalty_stamps_awarded >= 0),
  coupon_used_id uuid,
  discount_amount numeric DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  qr_code_data text,
  qr_scanned_at timestamp with time zone,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'refunded'::character varying]::text[])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id),
  CONSTRAINT transactions_loyalty_account_id_fkey FOREIGN KEY (loyalty_account_id) REFERENCES public.customer_loyalty_accounts(id),
  CONSTRAINT transactions_coupon_used_id_fkey FOREIGN KEY (coupon_used_id) REFERENCES public.coupons(id),
  CONSTRAINT transactions_app_user_id_fkey FOREIGN KEY (app_user_id) REFERENCES public.app_users(id)
);